# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'Tutor' do
pod 'SDWebImage', '~> 3.8.1'
pod 'MJRefresh', '~> 3.1.12'
pod 'SDAutoLayout', '~> 2.1.7'
pod 'PureLayout', '~> 3.0.2'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'SVProgressHUD', '~> 2.0.3'
pod 'AMap3DMap'
pod 'AMapSearch'
end

